trainer:
    accelerator: "gpu"
    max_epochs: 200
    overfit_batches: 0.0
    log_every_n_steps: 1
    num_sanity_val_steps: 0

data:
    target_sampling_rate: 16000
    use_preloaded_data: true

    dynamic_loading:
        base_dir_data:
        train_metadata_path:
        val_metadata_path:
        test_metadata_path:
        filename_column:

    preloaded_loading:
        dataset:
            train_preloaded_path: "../../data/ravdess_preloaded_wav2vec2_pooled/train"
            val_preloaded_path: "../../data/ravdess_preloaded_wav2vec2_pooled/val"
            test_preloaded_path: "../../data/ravdess_preloaded_wav2vec2_pooled/test"
            label_column: "label"
            embedding_column: "embedding"

        dataset2:
            train_preloaded_path:
            val_preloaded_path:
            test_preloaded_path:
            label_column:
            embedding_column:

            file_path_column:
            concatanation_type:

model:
    in_channels: 1
    mlp_input: 16320 # 1024 - mean, 16320 - flat
    output_size: 8
    dropout: 0.2
    mlp_output_dims: [1024]
    conv_layers: [
        [32, 3, 1],
        [64, 1, 1]
    ]
    global_pooling: "flat"

training:
    model_architecture: "cnn1d"
    lr: 1e-3
    scheduler_patience: 5
    batch_size: 16
    num_workers: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val_loss"
    dirpath: "../checkpoints/wav2vec2_classification_cnn1d_actor"

early_stopping:
    verbose: true
    monitor: "val_loss"
    patience: 100

encoder_version: "openai/whisper-base"

logger:
    project_name: "wav2vec2_classification_cnn1d_concept"
    debug: false
