trainer:
    accelerator: "gpu"
    max_epochs: 300
    overfit_batches: 0.0
    log_every_n_steps: 1
    num_sanity_val_steps: 0

data:
    target_sampling_rate: 16000
    use_preloaded_data: true

    dynamic_loading:
        base_dir_data:
        train_metadata_path:
        val_metadata_path:
        test_metadata_path:
        filename_column:

    preloaded_loading:
        dataset:
            train_preloaded_path: "../../ravdess_preloaded_whisper/train"
            val_preloaded_path: "../../ravdess_preloaded_whisper/val"
            test_preloaded_path: "../../ravdess_preloaded_whisper/test"
            label_column: "label"
            embedding_column: "embedding"

        dataset2:
            train_preloaded_path: "../../ravdess_preloaded_wav2vec2/train"
            val_preloaded_path: "../../ravdess_preloaded_wav2vec2/val"
            test_preloaded_path: "../../ravdess_preloaded_wav2vec2/test"
            label_column: "label"
            embedding_column: "embedding"

            file_path_column: "wav_file"
            concatanation_type: "channel"

model:
    in_channels: 2
    mlp_input: 16320 # 512 - mean, 7168 - flat
    output_size: 8
    dropout: 0.2
    mlp_output_dims: [1024]
    conv_layers: [
        [32, 3, 1],
        [64, 1, 1]
    ]
    global_pooling: "flat"

training:
    model_architecture: "cnn1d"
    lr: 1e-3
    scheduler_patience: 1
    batch_size: 16
    num_workers: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val_loss"
    dirpath: "../checkpoints/whisper_wav2vec2_classification_cnn1d_actor"

early_stopping:
    verbose: true
    monitor: "val_loss"
    patience: 25

encoder_version: "openai/whisper-base"

logger:
    project_name: "whisper_wav2vec2_classification_cnn1d_concept"
    debug: false
